# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('activity_type', models.CharField(choices=[('MZ', 'Moment of Zen'), ('IB', 'Icebreaker'), ('BR', 'Brainstorm'), ('DC', 'Discussion'), ('TB', 'Teambuilding')], default='Icebreaker', max_length=2)),
                ('num_people', models.IntegerField()),
                ('space_type', models.CharField(choices=[('R', 'Room'), ('V', 'Virtual')], default='Room', max_length=2)),
                ('activity_desc', models.CharField(max_length=1000)),
                ('variations', models.CharField(max_length=250)),
            ],
        ),
    ]
